### ISSUE TITLE
SamplingRate:22050にも対応して欲しい

### ISSUE THREAD

**Issue by Muacca** [jnory/MyShogiSoundPlayer#2]
MyShogiSoundPlayer.Sound.Playerの実装がSamplingRate=44100決めうちなので、SamplingRateが22050のwavだと早回しで再生されます。
PlayerのコンストラクタでSmaplingRateを指定できるようにし、MyShogiSoundPlayer.Manager.PlayManagerで44100用と22050用の２つのPlayerを保持、読み込んだwavのSamplingRateに合わせて呼び分けすれば解消するところまでは確認しました。
ただSamplingRateは他にもあるので、実装案としては強引すぎるのと、MyShogiSoundPlayerとしてどういうフォーマットに対応するのかの判断もあるかと思います。
要望として、issue立てておきます。

**Comment by jnory** [comment]
サンプルまでつけていただきありがとうございます！

今C言語で再生部分を書き直しておりその際にサンプリングレートに応じた値がセットされますので(https://github.com/jnory/MyShogiSoundPlayer/pull/4/files#diff-b27da96fed3f61be5cacfc5a01852305R149) 、自然に解消するように思えます。

ところで、SamplingRateが22050のファイルがあったのに気付きませんでした。
念のため動作確認したいのですが、どのファイルでしょうか…？

**Comment by Muacca** [comment]
Cで書き直して解消するなら、そちらの方が良いですね！

なお、22050のwavですが、matarilloさんの音素材ファイルの中にいくつかありました。
https://github.com/matarillo/MyShogiSound

例）99.wav、fu_a.wav

ご参考まで。お役に立てれば幸いです。

**Comment by jnory** [comment]
なるほど、そちらの音素材ですね。かしこまりました。次回リリース作業をするときには念のためそちらの音素材でも再生結果を確認するようにしたいと思います。

**Comment by jnory** [comment]
お手数をおかけしますがこちら https://github.com/jnory/MyShogiSoundPlayer/releases/tag/0.2.0 でお試しいただけますか…？私の環境では正常に再生されているように思います。

**Comment by Muacca** [comment]
https://github.com/jnory/MyShogiSoundPlayer/releases/tag/0.2.0 で試行したところ、22050の音声も再生されました！　特に他の問題も見当たりません。
issueをcloseします。
